version: "3.2"
services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    volumes:
      - cassandra:/var/lib/cassandra

  scalar-ledger:
    image: scalarlabs/scalar-ledger:1.3.1
    container_name: scalar-ledger
    depends_on:
      - cassandra
    environment:
      - SCALAR_CASSANDRA_HOST=cassandra
    ports:
      - "50051:50051"
      - "50052:50052"

  envoy:
    image: envoyproxy/envoy:v1.10.0
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8443:8443
    container_name: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./crt:/crt
      - ./key:/key
    depends_on:
      - scalar-ledger
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace

volumes:
  cassandra:

networks:
  default: